version: "3"

services:
  redis:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    container_name: redis-db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: "dockerfreelance.azurecr.io/celery_service:latest"
    container_name: celery-freelance
    command: celery -A celery_periodic_tasks worker --loglevel=info -B
