version: "3"

volumes:
  data:

services:
#  bot:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: "bot_service"
#    command: python ./bot/bot.py
#    volumes:
#      - /home/nikita-goncharov/Documents/Bot parser freelance sites/bot:/bot

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: "celery_service"
    command: celery -A celery_periodic_tasks worker --loglevel=info -B
    volumes:
      - /home/nikita-goncharov/Documents/Bot parser freelance sites/bot:/bot
      - /home/nikita-goncharov/Documents/Bot parser freelance sites/celery_periodic_tasks:/celery_periodic_tasks
      - /home/nikita-goncharov/Documents/Bot parser freelance sites/parser:/parser
