version: "3.9"

services:
  parser:
    build: .
    container_name: parser
    ports:
      - 7001:7001
    env_file:
      - .env
    command: "python -u -m debugpy --listen 0.0.0.0:7001 parser.py"
    volumes:
      - ./:/app
